# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Status.create id: 7, title: 'НА КОНТРОЛЕ'
Status.create id: 5, title: 'РЕШЕНО'
Status.create id: 4, title: 'В РАБОТЕ'

Category.create!([
                     {icon: "6", parent_id: "6", title: nil},
                     {icon: "6", parent_id: "6", title: nil},
                     {icon: "6", parent_id: "6", title: nil},
                     {icon: "20", parent_id: "20", title: nil},
                     {icon: "6", parent_id: "6", title: nil},
                     {icon: "6", parent_id: "6", title: nil},
                     {icon: "7", parent_id: "7", title: nil},
                     {icon: "23", parent_id: "23", title: nil},
                     {icon: "20", parent_id: "20", title: nil},
                     {icon: "20", parent_id: "20", title: nil},
                     {icon: "6", parent_id: "6", title: nil},
                     {icon: "20", parent_id: "20", title: nil},
                     {icon: "20", parent_id: "20", title: nil},
                     {icon: "6", parent_id: "6", title: nil},
                     {icon: "9", parent_id: "9", title: nil},
                     {icon: "11", parent_id: "11", title: nil},
                     {icon: "6", parent_id: "6", title: nil},
                     {icon: "20", parent_id: "20", title: nil},
                     {icon: "20", parent_id: "20", title: nil},
                     {icon: "6", parent_id: "6", title: nil},
                     {icon: "20", parent_id: "20", title: nil},
                     {icon: "7", parent_id: "7", title: nil},
                     {icon: "12", parent_id: "12", title: nil},
                     {icon: "20", parent_id: "20", title: nil},
                     {icon: "20", parent_id: "20", title: nil},
                     {icon: "6", parent_id: "6", title: nil},
                     {icon: "12", parent_id: "12", title: nil},
                     {icon: "22", parent_id: "22", title: nil},
                     {icon: "21", parent_id: "21", title: nil},
                     {icon: "7", parent_id: "7", title: nil},
                     {icon: "10", parent_id: "10", title: nil},
                     {icon: "10", parent_id: "10", title: nil},
                     {icon: "10", parent_id: "10", title: nil},
                     {icon: "11", parent_id: "11", title: nil},
                     {icon: "12", parent_id: "12", title: nil},
                     {icon: "7", parent_id: "7", title: nil},
                     {icon: "12", parent_id: "12", title: nil},
                     {icon: "14", parent_id: "14", title: nil},
                     {icon: "23", parent_id: "23", title: nil},
                     {icon: "9", parent_id: "9", title: nil},
                     {icon: "7", parent_id: "7", title: nil},
                     {icon: "13", parent_id: "13", title: nil},
                     {icon: "10", parent_id: "10", title: nil},
                     {icon: "6", parent_id: "6", title: nil},
                     {icon: "20", parent_id: "20", title: nil},
                     {icon: "7", parent_id: "7", title: nil},
                     {icon: "14", parent_id: "14", title: nil},
                     {icon: "13", parent_id: "13", title: nil},
                     {icon: "20", parent_id: "20", title: nil},
                     {icon: "6", parent_id: "6", title: nil},
                     {icon: "6", parent_id: "6", title: nil},
                     {icon: "14", parent_id: "14", title: nil},
                     {icon: "20", parent_id: "20", title: nil},
                     {icon: "21", parent_id: "21", title: nil},
                     {icon: "14", parent_id: "14", title: nil},
                     {icon: "14", parent_id: "14", title: nil},
                     {icon: "21", parent_id: "21", title: nil},
                     {icon: "10", parent_id: "10", title: nil},
                     {icon: "23", parent_id: "23", title: nil},
                     {icon: "7", parent_id: "7", title: nil},
                     {icon: "23", parent_id: "23", title: nil},
                     {icon: "21", parent_id: "21", title: nil},
                     {icon: "7", parent_id: "7", title: nil},
                     {icon: "6", parent_id: "6", title: nil},
                     {icon: "21", parent_id: "21", title: nil},
                     {icon: "11", parent_id: "11", title: nil},
                     {icon: "22", parent_id: "22", title: nil},
                     {icon: "23", parent_id: "23", title: nil},
                     {icon: "20", parent_id: "20", title: nil},
                     {icon: "20", parent_id: "20", title: nil},
                     {icon: "20", parent_id: "20", title: nil},
                     {icon: "13", parent_id: "13", title: nil},
                     {icon: "11", parent_id: "11", title: nil},
                     {icon: "20", parent_id: "20", title: nil},
                     {icon: "6", parent_id: "6", title: nil},
                     {icon: "11", parent_id: "11", title: nil},
                     {icon: "13", parent_id: "13", title: nil},
                     {icon: "20", parent_id: "20", title: nil},
                     {icon: "9", parent_id: "9", title: nil},
                     {icon: "10", parent_id: "10", title: nil},
                     {icon: "11", parent_id: "11", title: nil},
                     {icon: "23", parent_id: "23", title: nil},
                     {icon: "23", parent_id: "23", title: nil},
                     {icon: "11", parent_id: "11", title: nil},
                     {icon: "13", parent_id: "13", title: nil},
                     {icon: "6", parent_id: "6", title: nil}
                 ])
